package gui;

import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Admin
 */
public class ChuyenVienFrame extends javax.swing.JFrame {

    /**
     * Creates new form ChuyenVienFrame1
     */
    public ChuyenVienFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chuyenVienFramePanel = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        emsTxt = new javax.swing.JLabel();
        clc02Txt = new javax.swing.JLabel();
        categoryPanel = new javax.swing.JPanel();
        logoutBtn = new javax.swing.JLabel();
        duAnBtn = new javax.swing.JPanel();
        duAnTxt = new javax.swing.JLabel();
        duAnSidePanel = new javax.swing.JPanel();
        ttcnBtn = new javax.swing.JPanel();
        ttcnTxt = new javax.swing.JLabel();
        ttcnSidePanel = new javax.swing.JPanel();
        nhanVienBtn = new javax.swing.JPanel();
        nhanVienTxt = new javax.swing.JLabel();
        nhanVienSidePanel = new javax.swing.JPanel();
        tabPanel = new javax.swing.JTabbedPane();
        panelNhanVien = new javax.swing.JPanel();
        nhanVienScrollTable = new javax.swing.JScrollPane();
        nhanVienTable = new javax.swing.JTable();
        nhanVienSearchBar = new javax.swing.JTextField();
        nhanVienSearchBtn = new javax.swing.JButton();
        panelTTCN = new javax.swing.JPanel();
        maNVLabel = new javax.swing.JLabel();
        maNVField = new javax.swing.JLabel();
        hoTenLabel = new javax.swing.JLabel();
        hoTenField = new javax.swing.JLabel();
        gioiTinhLabel = new javax.swing.JLabel();
        gioiTinhField = new javax.swing.JLabel();
        ngaySinhLabel = new javax.swing.JLabel();
        ngaySinhField = new javax.swing.JLabel();
        sdtLabel = new javax.swing.JLabel();
        sdtField = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        emailField = new javax.swing.JLabel();
        luongCBLabel = new javax.swing.JLabel();
        luongCBField = new javax.swing.JLabel();
        phuCapLabel = new javax.swing.JLabel();
        phuCapField = new javax.swing.JLabel();
        ngayBDLabel = new javax.swing.JLabel();
        ngayBatDauField = new javax.swing.JLabel();
        panelDuAn = new javax.swing.JPanel();
        duAn1Tab = new javax.swing.JPanel();
        duAn2Tab = new javax.swing.JPanel();
        duAn3Tab = new javax.swing.JPanel();
        duAn4Tab = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EMS");
        setLocationByPlatform(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        chuyenVienFramePanel.setBackground(new java.awt.Color(205, 225, 238));
        chuyenVienFramePanel.setMaximumSize(new java.awt.Dimension(230, 632));
        chuyenVienFramePanel.setMinimumSize(new java.awt.Dimension(230, 632));
        chuyenVienFramePanel.setPreferredSize(new java.awt.Dimension(230, 632));
        chuyenVienFramePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headerPanel.setBackground(new java.awt.Color(74, 98, 138));
        headerPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        headerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        emsTxt.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        emsTxt.setForeground(new java.awt.Color(255, 255, 255));
        emsTxt.setText("EMS");
        headerPanel.add(emsTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        clc02Txt.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        clc02Txt.setForeground(new java.awt.Color(205, 225, 238));
        clc02Txt.setText("CLC-02");
        headerPanel.add(clc02Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        chuyenVienFramePanel.add(headerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 50));

        categoryPanel.setBackground(new java.awt.Color(144, 176, 194));
        categoryPanel.setMinimumSize(new java.awt.Dimension(240, 240));
        categoryPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoutBtn.setBackground(new java.awt.Color(0, 0, 0));
        logoutBtn.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        logoutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Logout.png"))); // NOI18N
        logoutBtn.setText("LOGOUT");
        logoutBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutBtnMouseEntered(evt);
            }
        });
        categoryPanel.add(logoutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 600, -1, -1));

        duAnBtn.setBackground(new java.awt.Color(205, 225, 238));
        duAnBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                duAnBtnMouseClicked(evt);
            }
        });
        duAnBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        duAnTxt.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        duAnTxt.setForeground(new java.awt.Color(74, 98, 138));
        duAnTxt.setText("Dự Án");
        duAnBtn.add(duAnTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 130, 50));

        duAnSidePanel.setBackground(new java.awt.Color(74, 98, 138));
        duAnBtn.add(duAnSidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 50));

        categoryPanel.add(duAnBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 240, 50));

        ttcnBtn.setBackground(new java.awt.Color(205, 225, 238));
        ttcnBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ttcnBtnMouseClicked(evt);
            }
        });
        ttcnBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ttcnTxt.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        ttcnTxt.setForeground(new java.awt.Color(74, 98, 138));
        ttcnTxt.setText("Thông tin Cá nhân");
        ttcnBtn.add(ttcnTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 180, 50));

        ttcnSidePanel.setBackground(new java.awt.Color(74, 98, 138));
        ttcnBtn.add(ttcnSidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 50));

        categoryPanel.add(ttcnBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 240, 50));

        nhanVienBtn.setBackground(new java.awt.Color(74, 98, 138));
        nhanVienBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nhanVienBtnMouseClicked(evt);
            }
        });
        nhanVienBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nhanVienTxt.setBackground(new java.awt.Color(205, 225, 238));
        nhanVienTxt.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        nhanVienTxt.setForeground(new java.awt.Color(255, 255, 255));
        nhanVienTxt.setText("Nhân Viên");
        nhanVienBtn.add(nhanVienTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 5, 150, 40));

        nhanVienSidePanel.setBackground(new java.awt.Color(255, 255, 255));
        nhanVienBtn.add(nhanVienSidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 50));

        categoryPanel.add(nhanVienBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 240, 50));

        chuyenVienFramePanel.add(categoryPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 42, 240, 700));

        panelNhanVien.setBackground(new java.awt.Color(228, 238, 244));
        panelNhanVien.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nhanVienTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        nhanVienScrollTable.setViewportView(nhanVienTable);

        panelNhanVien.add(nhanVienScrollTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 900, 470));

        nhanVienSearchBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nhanVienSearchBarActionPerformed(evt);
            }
        });
        panelNhanVien.add(nhanVienSearchBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 90, 240, -1));

        nhanVienSearchBtn.setText("jButton4");
        panelNhanVien.add(nhanVienSearchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 90, -1, -1));

        tabPanel.addTab("tab1", panelNhanVien);

        panelTTCN.setBackground(new java.awt.Color(228, 238, 244));
        panelTTCN.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        maNVLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        maNVLabel.setText("Mã Nhân Viên:");
        panelTTCN.add(maNVLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, -1, -1));

        maNVField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        maNVField.setText("null");
        panelTTCN.add(maNVField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, -1, -1));

        hoTenLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        hoTenLabel.setText("Họ và Tên:");
        panelTTCN.add(hoTenLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, -1, -1));

        hoTenField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        hoTenField.setText("null");
        panelTTCN.add(hoTenField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, -1, -1));

        gioiTinhLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        gioiTinhLabel.setText("Giới tính:");
        panelTTCN.add(gioiTinhLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, -1, -1));

        gioiTinhField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        gioiTinhField.setText("null");
        panelTTCN.add(gioiTinhField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, -1, -1));

        ngaySinhLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ngaySinhLabel.setText("Ngày sinh:");
        panelTTCN.add(ngaySinhLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, -1, -1));

        ngaySinhField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ngaySinhField.setText("null");
        panelTTCN.add(ngaySinhField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, -1, -1));

        sdtLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sdtLabel.setText("Số điện thoại:");
        panelTTCN.add(sdtLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, -1, -1));

        sdtField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sdtField.setText("null");
        panelTTCN.add(sdtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 380, -1, -1));

        emailLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        emailLabel.setText("Email:");
        panelTTCN.add(emailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 440, -1, -1));

        emailField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        emailField.setText("null");
        panelTTCN.add(emailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 440, -1, -1));

        luongCBLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        luongCBLabel.setText("Lương cơ bản:");
        panelTTCN.add(luongCBLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, -1, -1));

        luongCBField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        luongCBField.setText("null");
        panelTTCN.add(luongCBField, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 170, -1, -1));

        phuCapLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        phuCapLabel.setText("Phụ cấp:");
        panelTTCN.add(phuCapLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, -1, -1));

        phuCapField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        phuCapField.setText("null");
        panelTTCN.add(phuCapField, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 220, -1, -1));

        ngayBDLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ngayBDLabel.setText("Ngày bắt đầu làm việc:");
        panelTTCN.add(ngayBDLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, -1, -1));

        ngayBatDauField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ngayBatDauField.setText("null");
        panelTTCN.add(ngayBatDauField, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 270, -1, -1));

        tabPanel.addTab("tab2", panelTTCN);

        panelDuAn.setBackground(new java.awt.Color(228, 238, 244));
        panelDuAn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        duAn1Tab.setBackground(new java.awt.Color(255, 255, 255));
        duAn1Tab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                duAn1TabMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                duAn1TabMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                duAn1TabMouseExited(evt);
            }
        });
        panelDuAn.add(duAn1Tab, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 170, 110));

        duAn2Tab.setBackground(new java.awt.Color(255, 255, 255));
        duAn2Tab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                duAn2TabMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                duAn2TabMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                duAn2TabMouseExited(evt);
            }
        });
        panelDuAn.add(duAn2Tab, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 150, 170, 110));

        duAn3Tab.setBackground(new java.awt.Color(255, 255, 255));
        duAn3Tab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                duAn3TabMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                duAn3TabMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                duAn3TabMouseExited(evt);
            }
        });
        panelDuAn.add(duAn3Tab, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 170, 110));

        duAn4Tab.setBackground(new java.awt.Color(255, 255, 255));
        duAn4Tab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                duAn4TabMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                duAn4TabMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                duAn4TabMouseExited(evt);
            }
        });
        duAn4Tab.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelDuAn.add(duAn4Tab, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 170, 110));

        tabPanel.addTab("tab3", panelDuAn);

        chuyenVienFramePanel.add(tabPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, -40, 960, 730));

        getContentPane().add(chuyenVienFramePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 690));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void duAn4TabMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_duAn4TabMouseExited
        // TODO add your handling code here:
        duAn4Tab.setBackground( new Color(255, 255, 255));
    }//GEN-LAST:event_duAn4TabMouseExited

    private void duAn4TabMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_duAn4TabMouseEntered
        // TODO add your handling code here:
        duAn4Tab.setBackground( new Color(112, 132, 165));
    }//GEN-LAST:event_duAn4TabMouseEntered

    private void duAn4TabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_duAn4TabMouseClicked
        // TODO add your handling code here:

        new ChuyenVienFrameDuAn().setVisible(true);
    }//GEN-LAST:event_duAn4TabMouseClicked

    private void duAn3TabMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_duAn3TabMouseExited
        // TODO add your handling code here:
        duAn3Tab.setBackground( new Color(255, 255, 255));
    }//GEN-LAST:event_duAn3TabMouseExited

    private void duAn3TabMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_duAn3TabMouseEntered
        // TODO add your handling code here:
        duAn3Tab.setBackground( new Color(112, 132, 165));
    }//GEN-LAST:event_duAn3TabMouseEntered

    private void duAn3TabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_duAn3TabMouseClicked
        // TODO add your handling code here:
        new ChuyenVienFrameDuAn().setVisible(true);
    }//GEN-LAST:event_duAn3TabMouseClicked

    private void duAn2TabMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_duAn2TabMouseExited
        // TODO add your handling code here:
        duAn2Tab.setBackground( new Color(255, 255, 255));
    }//GEN-LAST:event_duAn2TabMouseExited

    private void duAn2TabMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_duAn2TabMouseEntered
        // TODO add your handling code here:
        duAn2Tab.setBackground( new Color(112, 132, 165));
    }//GEN-LAST:event_duAn2TabMouseEntered

    private void duAn2TabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_duAn2TabMouseClicked
        // TODO add your handling code here:
        new ChuyenVienFrameDuAn().setVisible(true);
    }//GEN-LAST:event_duAn2TabMouseClicked

    private void duAn1TabMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_duAn1TabMouseExited
        // TODO add your handling code here:
        duAn1Tab.setBackground( new Color(255, 255, 255));
    }//GEN-LAST:event_duAn1TabMouseExited

    private void duAn1TabMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_duAn1TabMouseEntered
        // TODO add your handling code here:
        duAn1Tab.setBackground( new Color(112, 132, 165));
    }//GEN-LAST:event_duAn1TabMouseEntered

    private void duAn1TabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_duAn1TabMouseClicked
        // TODO add your handling code here:
        new ChuyenVienFrameDuAn().setVisible(true);
    }//GEN-LAST:event_duAn1TabMouseClicked

    private void nhanVienSearchBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nhanVienSearchBarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nhanVienSearchBarActionPerformed

    private void logoutBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBtnMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutBtnMouseEntered

    private void logoutBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBtnMouseClicked
        // TODO add your handling code here:
        int tmp = JOptionPane.showConfirmDialog(this,"Confirm Logout?", "Logout", JOptionPane.YES_NO_OPTION);
        if ( tmp == 0 ) {
            new Login().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_logoutBtnMouseClicked

    private void nhanVienBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nhanVienBtnMouseClicked
        nhanVienBtn.setBackground(new Color(74, 98, 138));
        nhanVienTxt.setForeground(new Color(255, 255, 255));
        nhanVienSidePanel.setBackground(new Color(255, 255, 255));
        
        ttcnBtn.setBackground(new Color(205,225,238));
        ttcnTxt.setForeground(new Color(74,98,138));
        ttcnSidePanel.setBackground(new Color(74,98,138));
        
        duAnBtn.setBackground(new Color(205,225,238));
        duAnTxt.setForeground(new Color(74,98,138));
        duAnSidePanel.setBackground(new Color(74,98,138));
        
        tabPanel.setSelectedIndex(0);        
    }//GEN-LAST:event_nhanVienBtnMouseClicked

    private void ttcnBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ttcnBtnMouseClicked
        ttcnBtn.setBackground(new Color(74, 98, 138));
        ttcnTxt.setForeground(new Color(255, 255, 255));
        ttcnSidePanel.setBackground(new Color(255, 255, 255));
        
        nhanVienBtn.setBackground(new Color(205,225,238));
        nhanVienTxt.setForeground(new Color(74,98,138));
        nhanVienSidePanel.setBackground(new Color(74,98,138));
        
        duAnBtn.setBackground(new Color(205,225,238));
        duAnTxt.setForeground(new Color(74,98,138));
        duAnSidePanel.setBackground(new Color(74,98,138));
        
        tabPanel.setSelectedIndex(1);
    }//GEN-LAST:event_ttcnBtnMouseClicked

    private void duAnBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_duAnBtnMouseClicked
        duAnBtn.setBackground(new Color(74, 98, 138));
        duAnTxt.setForeground(new Color(255, 255, 255));
        duAnSidePanel.setBackground(new Color(255, 255, 255));
        
        nhanVienBtn.setBackground(new Color(205,225,238));
        nhanVienTxt.setForeground(new Color(74,98,138));
        nhanVienSidePanel.setBackground(new Color(74,98,138));
        
        ttcnBtn.setBackground(new Color(205,225,238));
        ttcnTxt.setForeground(new Color(74,98,138));
        ttcnSidePanel.setBackground(new Color(74,98,138));
        tabPanel.setSelectedIndex(2);
    }//GEN-LAST:event_duAnBtnMouseClicked
     
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChuyenVienFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChuyenVienFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChuyenVienFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChuyenVienFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChuyenVienFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel categoryPanel;
    private javax.swing.JPanel chuyenVienFramePanel;
    private javax.swing.JLabel clc02Txt;
    private javax.swing.JPanel duAn1Tab;
    private javax.swing.JPanel duAn2Tab;
    private javax.swing.JPanel duAn3Tab;
    private javax.swing.JPanel duAn4Tab;
    private javax.swing.JPanel duAnBtn;
    private javax.swing.JPanel duAnSidePanel;
    private javax.swing.JLabel duAnTxt;
    private javax.swing.JLabel emailField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel emsTxt;
    private javax.swing.JLabel gioiTinhField;
    private javax.swing.JLabel gioiTinhLabel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel hoTenField;
    private javax.swing.JLabel hoTenLabel;
    private javax.swing.JLabel logoutBtn;
    private javax.swing.JLabel luongCBField;
    private javax.swing.JLabel luongCBLabel;
    private javax.swing.JLabel maNVField;
    private javax.swing.JLabel maNVLabel;
    private javax.swing.JLabel ngayBDLabel;
    private javax.swing.JLabel ngayBatDauField;
    private javax.swing.JLabel ngaySinhField;
    private javax.swing.JLabel ngaySinhLabel;
    private javax.swing.JPanel nhanVienBtn;
    private javax.swing.JScrollPane nhanVienScrollTable;
    private javax.swing.JTextField nhanVienSearchBar;
    private javax.swing.JButton nhanVienSearchBtn;
    private javax.swing.JPanel nhanVienSidePanel;
    private javax.swing.JTable nhanVienTable;
    private javax.swing.JLabel nhanVienTxt;
    private javax.swing.JPanel panelDuAn;
    private javax.swing.JPanel panelNhanVien;
    private javax.swing.JPanel panelTTCN;
    private javax.swing.JLabel phuCapField;
    private javax.swing.JLabel phuCapLabel;
    private javax.swing.JLabel sdtField;
    private javax.swing.JLabel sdtLabel;
    private javax.swing.JTabbedPane tabPanel;
    private javax.swing.JPanel ttcnBtn;
    private javax.swing.JPanel ttcnSidePanel;
    private javax.swing.JLabel ttcnTxt;
    // End of variables declaration//GEN-END:variables
}
